#include <p12f675.inc>
processor 12F675

RP0 EQU 5
GP0 EQU 0
GP1 EQU 1
GP2 EQU 2
GP3 EQU 3
GP4 EQU 4
GP5 EQU 5
TH EQU 0X20
TL EQU 0X22
U1H EQU 0X23
U1L EQU 0X24
U2H EQU 0X25
U2L EQU 0X26
TEMP EQU 0X21

ORG 0X00
	    GOTO START
ORG 0XFF
START
	    BCF STATUS, RP0
	    MOVLW 0X07
	    MOVWF CMCON
	    BSF STATUS, RP0
	    BCF TRISIO, GP0
	    BCF TRISIO, GP1
	    BCF TRISIO, GP2
	    BSF TRISIO, GP4
	    MOVLW b'01011000'
	    MOVWF ANSEL
	    BCF STATUS, RP0
	    MOVLW b'10001100'
	    MOVWF ADCON0
	     BSF ADCON0,ADON
	     MOVLW .2
	     MOVWF U1H
	     MOVLW .52
	     MOVWF U1L
	     MOVLW .0
	     MOVWF U2H
	     MOVLW .119
	     MOVWF U2L
F_1	   
	    BSF ADCON0,ADON
	    MOVLW .20
	    MOVWF TEMP
	    BSF ADCON0,1
	    DECFSZ TEMP
	    GOTO $-1
	    BCF ADCON0,ADON
	    BSF STATUS, RP0
	    MOVF ADRESL,W
	    MOVWF TL
	    BCF STATUS, RP0
	    MOVF ADRESH,W
	    MOVWF TH
	    MOVF U1H,W
	    SUBWF TH,W
	    BTFSS STATUS,C
	    GOTO F_2
	    BTFSC STATUS,Z
	    GOTO F_3
F_4	    
	    BCF GPIO,GP0
	    BSF GPIO,GP1
	    BSF GPIO,GP2
	    GOTO F_1
F_2		
		BTFSs TH,1
	    BTFSC TH,0
	    GOTO $+5
	    MOVF U2L,W
	    SUBWF TL,W
	    BTFSS STATUS,C
	    GOTO $+5
	    BSF GPIO,GP0
	    BCF GPIO,GP1
	    BSF GPIO,GP2
	    GOTO F_1
	    BSF GPIO,GP0
	    BSF GPIO,GP1
	    BCF GPIO,GP2
	    GOTO F_1
	    
F_3	    
	    MOVF U1L,W
	    SUBWF TL,W
	    BTFSS STATUS,C
	    GOTO F_2
	    GOTO F_4
END
	    
	    