 ;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   ѕт окт 21 2016
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================
      DEST_IND     DATA P1
      DESTINATION  DATA 24h
      MESSAGE      DATA 25h
      THIS_ADDRESS DATA 22h
      RCVD_ADDRESS DATA 23h 
      ADDRESS_SEND BIT  21h.0
      DATA_SEND    BIT  21h.1
      IS_SLAVE_SRC BIT  21h.2
      RECIEVED_MSG DATA 20h
      ALLOW_WRITE  BIT  P3.7
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start
      
      org   000bh
	 jmp ButtonSend
      org   001bh
	 reti
      org   0023h
	 jmp SerialHandle
      

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:	
           ;Write your code here

      setb EX1
      setb ES      
      setb EA
      setb ET0
      setb IT1
      
      setb sm0 
      setb sm1 
      clr  sm2 
      
      
      setb ren 
      clr  tb8 
      clr  rb8 
      orl  pcon,#128
      
      mov  THIS_ADDRESS, #0
      mov  TH1, #0FDh
      mov  TL0, #0FFh
      mov  TH0, #0FFh
      mov  TMOD,#00100110b
      setb TR1
      setb TR0
      clr  ADDRESS_SEND
Loop:	
      jmp Loop

ButtonSend:
       clr IS_SLAVE_SRC
       clr TF0
       clr IE1
       mov MESSAGE, P2
       jnb ALLOW_WRITE, SendRet
       call SetDestination
       call Send
       SendRet:
	 reti

   
      
Send: 
      mov DEST_IND, DESTINATION
      clr DATA_SEND
      clr TB8      
      cpl ADDRESS_SEND
      mov SBUF, DESTINATION
      ret
SerialHandle:
      jb  TI, TransmitComplete
      jb  RI, ReadComplete
      jmp HandleEnd
      TransmitComplete:
         clr TI
	 jb   DATA_SEND, HandleEnd
	 ;jnb  ADDRESS_SEND, HandleEnd
	 ;cpl  ADDRESS_SEND
	 setb TB8
	 mov  SBUF, MESSAGE
	 setb DATA_SEND
	 jmp  HandleEnd
      ReadComplete:
         clr RI
	 jb RB8, ReadData 
	 ReadAddress:
	    mov P1, SBUF
	    mov RCVD_ADDRESS, SBUF
	    mov  a, RCVD_ADDRESS
	    jmp HandleEnd
	 ReadData:
	    mov  a, RCVD_ADDRESS
	    cjne a, THIS_ADDRESS, SendToSlaves
	    mov  a, SBUF
	    rl   a
	    rl   a
	    rl   a 
	    rl   a
	    anl  a, #11110000b
	    orl  a, DEST_IND
	    mov  DEST_IND, a
	    jmp HandleEnd
	 SendToSlaves:
	    mov MESSAGE, SBUF
	    mov DESTINATION, RCVD_ADDRESS
	    call Send
      HandleEnd:
	    reti
SetDestination:
      mov a, P0
      mov DESTINATION, P0
      inc DESTINATION	
      ret
	 
	 
;====================================================================
      END
